import Header from "@/components/header/Header";
import Carousel from "@/components/header/carousel/Carousel";
import Navbar from "@/components/navbar/Navbar";
import "@/styles/globals.scss";
import type { AppProps } from "next/app";
import { Lato } from "next/font/google";
import Head from "next/head";
import { Fragment } from "react";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Fragment>
      <Head>
        <title>Nike clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          type="image/png"
          sizes="120x120"
          rel="icon"
          href="icons8-nike-120.png"
        />
      </Head>
      <style jsx global>{`
        html {
          font-family: ${lato.style.fontFamily};
        }
      `}</style>
        <Navbar />
        <Header/>
        <Carousel/>
        <Component {...pageProps} />
    </Fragment>
  );
}
